# pyright: reportUnknownVariableType=false
# pyright: reportUnknownMemberType=false
# pyright: reportUntypedFunctionDecorator=false
# pyright: reportDeprecated=false
from __future__ import annotations

from datetime import datetime
from sqlalchemy import select
from sqlalchemy.orm import Session

from app.db.models import DreamEntry, Save
from app.db.session import engine
from app.workers.celery_app import celery_app
from app.ws.v1 import append_typed_event


@celery_app.task(name="app.workers.tasks.dreams.task_12_generate_dream_entry")
def task_12_generate_dream_entry(
    user_id: str,
    save_id: str,
    kind: str = "dream",
    content: str | None = None,
) -> dict[str, object]:
    now = datetime.utcnow()
    final_kind = (kind or "dream").strip() or "dream"
    final_content = (content or "generated by task-12").strip() or "generated by task-12"

    with Session(engine) as db:
        entry = DreamEntry(
            save_id=save_id,
            kind=final_kind,
            content=final_content,
            created_at=now,
        )
        db.add(entry)
        db.commit()
        db.refresh(entry)
        entry_id = entry.id

    frame = append_typed_event(
        (user_id, save_id),
        frame_type="TIMELINE_EVENT",
        payload={
            "event": "DREAM_ENTRY_CREATED",
            "dream_entry": {
                "id": entry_id,
                "save_id": save_id,
                "kind": final_kind,
                "content": final_content,
                "created_at": now.isoformat() + "Z",
            },
        },
        ack_required=True,
    )

    return {
        "dream_entry_id": entry_id,
        "ws_frame": {
            "type": frame["type"],
            "seq": frame["seq"],
            "server_event_id": frame["server_event_id"],
        },
    }


@celery_app.task(name="app.workers.tasks.dreams.task_12_generate_dreams_for_all_saves")
def task_12_generate_dreams_for_all_saves(limit: int = 20) -> dict[str, object]:
    created: list[str] = []
    with Session(engine) as db:
        stmt = (
            select(Save)
            .where(Save.deleted_at.is_(None))
            .order_by(Save.created_at.desc())
            .limit(int(limit))
        )
        saves = [row for row in db.execute(stmt).scalars().all()]

        for s in saves:
            now = datetime.utcnow()
            entry = DreamEntry(
                save_id=s.id,
                kind="dream",
                content="generated by task-12 periodic",
                created_at=now,
            )
            db.add(entry)
            db.flush()
            created.append(entry.id)

            _ = append_typed_event(
                (s.user_id, s.id),
                frame_type="JOB_STATUS",
                payload={
                    "job": "task_12_generate_dreams_for_all_saves",
                    "status": "created",
                    "dream_entry_id": entry.id,
                    "save_id": s.id,
                    "created_at": now.isoformat() + "Z",
                },
                ack_required=True,
            )

        db.commit()

    return {"created_count": len(created), "dream_entry_ids": created}
