"""create beta tables

Revision ID: f1dcf9f0abe6
Revises: 6db398364679
Create Date: 2026-02-15 08:48:05.616622

"""

from __future__ import annotations

from alembic import op
import sqlalchemy as sa

# 迁移中显式引用自定义 Vector 类型，避免 autogenerate 生成的 `app.db.models.Vector(...)`
# 在未导入 app 包时导致 NameError。
from app.db.models import Vector


# revision identifiers, used by Alembic.
revision = "f1dcf9f0abe6"
down_revision = "6db398364679"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # pgvector 类型依赖扩展；必须在创建任何 vector(...) 列之前执行。
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")

    _ = op.create_table(
        "admin_kv",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("namespace", sa.String(length=50), nullable=False),
        sa.Column("key", sa.String(length=100), nullable=False),
        sa.Column("value_json", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("namespace", "key", name="uq_admin_kv_namespace_key"),
    )
    op.create_index(op.f("ix_admin_kv_namespace"), "admin_kv", ["namespace"], unique=False)
    _ = op.create_table(
        "admin_users",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=False),
        sa.Column("role", sa.String(length=20), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_admin_users_email"), "admin_users", ["email"], unique=True)
    _ = op.create_table(
        "audit_logs",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("actor", sa.String(length=50), nullable=False),
        sa.Column("action", sa.String(length=100), nullable=False),
        sa.Column("target_type", sa.String(length=50), nullable=False),
        sa.Column("target_id", sa.String(length=36), nullable=False),
        sa.Column("metadata_json", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_audit_logs_target_id"), "audit_logs", ["target_id"], unique=False)
    _ = op.create_table(
        "personas",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("prompt", sa.Text(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_personas_name"), "personas", ["name"], unique=True)
    _ = op.create_table(
        "plugin_packages",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("plugin_id", sa.String(length=200), nullable=False),
        sa.Column("version", sa.String(length=50), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("entry", sa.String(length=100), nullable=False),
        sa.Column("permissions_json", sa.Text(), nullable=False),
        sa.Column("manifest_json", sa.Text(), nullable=False),
        sa.Column("code_text", sa.Text(), nullable=False),
        sa.Column("sha256", sa.String(length=64), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("plugin_id", "version", name="uq_plugin_package_plugin_version"),
    )
    op.create_index(
        op.f("ix_plugin_packages_plugin_id"), "plugin_packages", ["plugin_id"], unique=False
    )
    op.create_index(op.f("ix_plugin_packages_status"), "plugin_packages", ["status"], unique=False)
    _ = op.create_table(
        "rooms",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("room_type", sa.String(length=50), nullable=False),
        sa.Column("created_by_user_id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["created_by_user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_rooms_created_by_user_id"), "rooms", ["created_by_user_id"], unique=False
    )
    _ = op.create_table(
        "saves",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_saves_user_id"), "saves", ["user_id"], unique=False)
    _ = op.create_table(
        "timeline_events",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("save_id", sa.String(length=64), nullable=False),
        sa.Column("event_type", sa.String(length=50), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_timeline_events_save_id"), "timeline_events", ["save_id"], unique=False
    )
    op.create_index(
        op.f("ix_timeline_events_user_id"), "timeline_events", ["user_id"], unique=False
    )
    _ = op.create_table(
        "ugc_assets",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("uploaded_by_user_id", sa.String(length=36), nullable=False),
        sa.Column("asset_type", sa.String(length=50), nullable=False),
        sa.Column("manifest_json", sa.Text(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("storage_path", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["uploaded_by_user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_ugc_assets_status"), "ugc_assets", ["status"], unique=False)
    op.create_index(
        op.f("ix_ugc_assets_uploaded_by_user_id"),
        "ugc_assets",
        ["uploaded_by_user_id"],
        unique=False,
    )
    _ = op.create_table(
        "dream_entries",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("save_id", sa.String(length=36), nullable=False),
        sa.Column("kind", sa.String(length=20), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["save_id"], ["saves.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_dream_entries_save_id"), "dream_entries", ["save_id"], unique=False)
    _ = op.create_table(
        "gallery_items",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("save_id", sa.String(length=36), nullable=False),
        sa.Column("prompt", sa.Text(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("storage_dir", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("completed_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(["save_id"], ["saves.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_gallery_items_save_id"), "gallery_items", ["save_id"], unique=False)
    _ = op.create_table(
        "knowledge_materials",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("save_id", sa.String(length=36), nullable=False),
        sa.Column("filename", sa.String(length=255), nullable=False),
        sa.Column("content_type", sa.String(length=100), nullable=True),
        sa.Column("storage_path", sa.Text(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["save_id"], ["saves.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_knowledge_materials_save_id"), "knowledge_materials", ["save_id"], unique=False
    )
    _ = op.create_table(
        "memory_items",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("save_id", sa.String(length=36), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("source", sa.String(length=100), nullable=True),
        sa.Column("trusted", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(["save_id"], ["saves.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_memory_items_save_id"), "memory_items", ["save_id"], unique=False)
    _ = op.create_table(
        "room_members",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("room_id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("role", sa.String(length=20), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("joined_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(["room_id"], ["rooms.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("room_id", "user_id", name="uq_room_member_room_user"),
    )
    op.create_index(op.f("ix_room_members_room_id"), "room_members", ["room_id"], unique=False)
    op.create_index(op.f("ix_room_members_user_id"), "room_members", ["user_id"], unique=False)
    _ = op.create_table(
        "save_persona_bindings",
        sa.Column("save_id", sa.String(length=36), nullable=False),
        sa.Column("persona_id", sa.String(length=36), nullable=False),
        sa.Column("bound_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["persona_id"], ["personas.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["save_id"], ["saves.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("save_id"),
    )
    op.create_index(
        op.f("ix_save_persona_bindings_persona_id"),
        "save_persona_bindings",
        ["persona_id"],
        unique=False,
    )
    _ = op.create_table(
        "knowledge_chunks",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("material_id", sa.String(length=36), nullable=False),
        sa.Column("save_id", sa.String(length=36), nullable=False),
        sa.Column("chunk_index", sa.Integer(), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("embedding_model", sa.String(length=50), nullable=False),
        sa.Column("embedding_dim", sa.Integer(), nullable=False),
        sa.Column("embedding", Vector(64), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["material_id"], ["knowledge_materials.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["save_id"], ["saves.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("material_id", "chunk_index", name="uq_knowledge_chunk_material_index"),
    )
    op.create_index(
        op.f("ix_knowledge_chunks_material_id"), "knowledge_chunks", ["material_id"], unique=False
    )
    op.create_index(
        op.f("ix_knowledge_chunks_save_id"), "knowledge_chunks", ["save_id"], unique=False
    )
    _ = op.create_table(
        "memory_embeddings",
        sa.Column("memory_id", sa.String(length=36), nullable=False),
        sa.Column("embedding_model", sa.String(length=50), nullable=False),
        sa.Column("embedding_dim", sa.Integer(), nullable=False),
        sa.Column("embedding", Vector(64), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["memory_id"], ["memory_items.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("memory_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("memory_embeddings")
    op.drop_index(op.f("ix_knowledge_chunks_save_id"), table_name="knowledge_chunks")
    op.drop_index(op.f("ix_knowledge_chunks_material_id"), table_name="knowledge_chunks")
    op.drop_table("knowledge_chunks")
    op.drop_index(op.f("ix_save_persona_bindings_persona_id"), table_name="save_persona_bindings")
    op.drop_table("save_persona_bindings")
    op.drop_index(op.f("ix_room_members_user_id"), table_name="room_members")
    op.drop_index(op.f("ix_room_members_room_id"), table_name="room_members")
    op.drop_table("room_members")
    op.drop_index(op.f("ix_memory_items_save_id"), table_name="memory_items")
    op.drop_table("memory_items")
    op.drop_index(op.f("ix_knowledge_materials_save_id"), table_name="knowledge_materials")
    op.drop_table("knowledge_materials")
    op.drop_index(op.f("ix_gallery_items_save_id"), table_name="gallery_items")
    op.drop_table("gallery_items")
    op.drop_index(op.f("ix_dream_entries_save_id"), table_name="dream_entries")
    op.drop_table("dream_entries")
    op.drop_index(op.f("ix_ugc_assets_uploaded_by_user_id"), table_name="ugc_assets")
    op.drop_index(op.f("ix_ugc_assets_status"), table_name="ugc_assets")
    op.drop_table("ugc_assets")
    op.drop_index(op.f("ix_timeline_events_user_id"), table_name="timeline_events")
    op.drop_index(op.f("ix_timeline_events_save_id"), table_name="timeline_events")
    op.drop_table("timeline_events")
    op.drop_index(op.f("ix_saves_user_id"), table_name="saves")
    op.drop_table("saves")
    op.drop_index(op.f("ix_rooms_created_by_user_id"), table_name="rooms")
    op.drop_table("rooms")
    op.drop_index(op.f("ix_plugin_packages_status"), table_name="plugin_packages")
    op.drop_index(op.f("ix_plugin_packages_plugin_id"), table_name="plugin_packages")
    op.drop_table("plugin_packages")
    op.drop_index(op.f("ix_personas_name"), table_name="personas")
    op.drop_table("personas")
    op.drop_index(op.f("ix_audit_logs_target_id"), table_name="audit_logs")
    op.drop_table("audit_logs")
    op.drop_index(op.f("ix_admin_users_email"), table_name="admin_users")
    op.drop_table("admin_users")
    op.drop_index(op.f("ix_admin_kv_namespace"), table_name="admin_kv")
    op.drop_table("admin_kv")
    # ### end Alembic commands ###
